<?php

/*
 =========================== - - - - - - - =================
 Contact Custom Meta Field | cob_contacts | contact_location
 ========================== - - - - - - - ==================
*/

function COB_Services_Contacts_meta_box() {
  add_meta_box('contact_location', 'Office Location', 'cob_contact_location_callback', 'cob_contacts', 'side' );
}

add_action( 'add_meta_boxes', 'COB_Services_Contacts_meta_box');

// Callback Function
function cob_contact_location_callback( $post ){
  // Create nonce field
  wp_nonce_field('cob_save_contact_location_data', 'cob_contact_location_meta_box_nonce');
  $value = get_post_meta( $post->ID, '_cob_contact_location_value_key', true);

  // Print Input Box
  echo '<label for="cob_contact_location_field">Office Location of Contact</label>';
  echo '<input type="text" id="cob_contact_location_field" name="cob_contact_location_field" value="' . esc_attr($value) . '" size="15" />';
}

// Save function
function cob_save_contact_location_data( $post_id ){

  // Check if nonce was set when 'save button' is clicked - security
  if( ! isset( $_POST['cob_contact_location_meta_box_nonce'])){
    return; // hard stop to prevent malicious data
  }

  // Check if nonce was generated by wordpress, not manually
  if ( ! wp_verify_nonce( $_POST['cob_contact_location_meta_box_nonce'], 'cob_save_contact_location_data' )){
    return;
  }

  // Verify user has correct permission to write data
  if ( ! current_user_can('edit_post', $post_id)){
    return;
  }

  // Verify data is actually in the box
  if( ! isset( $_POST['cob_contact_location_field'])){
    return;
  }

  // Sanatize the data before saving it
  $custom_data = sanitize_text_field( $_POST['cob_contact_location_field'] );

  update_post_meta( $post_id, '_cob_contact_location_value_key', $custom_data);

}

add_action( 'save_post', 'cob_save_contact_location_data');


/*
 =========================== - - - - - - - =================
 Contact Custom Meta Field | forms pg(ID = 191) | forms_title
 ========================== - - - - - - - ==================
*/

function COB_Services_forms_title_meta_box() {
  add_meta_box('forms_title', 'Post Form Title', 'cob_forms_title_callback', 'forms' );
}

add_action( 'add_meta_boxes', 'COB_Services_forms_title_meta_box');

// Callback Function
function cob_forms_title_callback( $post ){
  // Create nonce field
  wp_nonce_field('cob_save_forms_title_data', 'cob_forms_title_meta_box_nonce');
  $value = get_post_meta( $post->ID, '_cob_forms_title_value_key', true);

  // Print Input Box
  echo '<label for="cob_contact_location_field">Office Location of Contact</label>';
  echo '<input type="text" id="cob_contact_location_field" name="cob_contact_location_field" value="' . esc_attr($value) . '" size="15" />';
}

// // Save function
// function cob_save_contact_location_data( $post_id ){
//
//   // Check if nonce was set when 'save button' is clicked - security
//   if( ! isset( $_POST['cob_contact_location_meta_box_nonce'])){
//     return; // hard stop to prevent malicious data
//   }
//
//   // Check if nonce was generated by wordpress, not manually
//   if ( ! wp_verify_nonce( $_POST['cob_contact_location_meta_box_nonce'], 'cob_save_contact_location_data' )){
//     return;
//   }
//
//   // Verify user has correct permission to write data
//   if ( ! current_user_can('edit_post', $post_id)){
//     return;
//   }
//
//   // Verify data is actually in the box
//   if( ! isset( $_POST['cob_contact_location_field'])){
//     return;
//   }
//
//   // Sanatize the data before saving it
//   $custom_data = sanitize_text_field( $_POST['cob_contact_location_field'] );
//
//   update_post_meta( $post_id, '_cob_contact_location_value_key', $custom_data);
//
// }
//
// add_action( 'save_post', 'cob_save_contact_location_data');
